### ISSUE TITLE
No favorites message

### ISSUE THREAD

**Issue by vycius** [GotPet/getpet-android#2]
![screenshot_20181108-150538_get pet](https://user-images.githubusercontent.com/3719141/48200554-2912c500-e368-11e8-9cda-8fd152c47f69.jpg)
Empty message for no favorites.

**Comment by GretaGri** [comment]
I think we also need an option to remove an item from favorites.

**Comment by vycius** [comment]
Yes. Possibly in the future we should consider adding possibility to remove favorite, but this issue is unrelated to it.
